GET http://localhost:8081/message/messages?receiverId=1&limit=20&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzg2NzgwMzEsInJvbGUiOiJhZG1pbiIsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJ6b3JvIn0.LtdKeV2vJ8xv80WS8pZbFJbzUhMiLZimoLQfq2_C6I4