curl.exe -X POST http://localhost:8080/products/new-product `
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc4ODk2ODksInJvbGUiOiJhZG1pbiIsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJUZXN0ZXIifQ.rl5qV9nxuaeXl_3WRtrHmZRFAZNRNSVdQmdadYSsAOI" `
-F "name=Tractor seeds" `
-F "description=sunflower chia seeds " `
-F "userId=1" `
-F "categoryName=seeds" `
-F "price= 500"
-F "image=@C:/Users/Administrator/Pictures/task.jpg" 