DELETE http://localhost:8080/products/delete-product/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc0NjgxMDEsInJvbGUiOiJzZWxsZXIiLCJ1c2VySWQiOjIsInVzZXJuYW1lIjoiVGVzdGVyIn0.DqyVB7SmAYWctCQwVadok1hxE4JI2TfNsGGnvvo1SvY