GET http://localhost:8080/products/get-Product/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzcxNDQ4ODAsInJvbGUiOiJzZWxsZXIiLCJ1c2VySWQiOjIsInVzZXJuYW1lIjoiVGVzdGVyIn0.Zm2cFG1mMBP7VbSEEKl3ks8ZbMaGE1vq48v8N65mzAs