GET http://localhost:8080/products/get-Product/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckB0ZXN0LmNvbSIsImV4cCI6MTczNTIxMDU1NiwidXNlcklkIjoxfQ.7Pb9_hrIo978EpAnMsUgdRy72wHhPmjgB2jBfsx_u4I