PUT http://localhost:8080/products/update-product/10
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpvcnhAdGVzdC5jb20iLCJleHAiOjE3MzI5Njk1MjUsInVzZXJJZCI6Mn0.vNJjG3e5iZ8a_VYrFa1SOLrQ3Fx77i1CITPdfB-HR1o

{
    "name":"mordsadx",
    "description": "moshsi sadsvent", 
    "imagepath" : "new location",
    "userId" : 0
}