PUT http://localhost:8080/products/update-product/1
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckB0ZXN0LmNvbSIsImV4cCI6MTczNTIxMzEzMiwidXNlcklkIjoxfQ.MyS8EBudzbEGZR4dlWXJLAWHKkLawngM1xs9tVWWLOQ

{
    "name":"",
    "description": "", 
    "imagepath" : "xc",
    "userId" : 0,
    "categoryId" : 0
}