PUT http://localhost:8080/products/update-product/1
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY4NDM0NTAsInJvbGUiOiJjdXN0b21lciIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJUZXN0ZXIyIn0.RlhyO0le627JHe_VWBR1x_xEPqZg7XmCSdkJ3tQ5alY

{
    "name":"machinery for farming"

}