curl.exe -X POST http://localhost:8080/category/new-category `
-H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDcwOTQsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJUZXN0ZXIyIn0.6xKMDdiAVt-mC6jFYhL3wl3MgBi9L1tvPX2TfMOGv-Y" `
-F "name=random seeddss" `
-F "description=SOme sunflower seedssdsdsd" `
-F "image=@C:/Users/Administrator/Pictures/task.jpg"`
-F "user_id=1" 