GET http://localhost:8080/category/get-Category/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MTMxMjcsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJUZXN0ZXIyIn0.tfBX_H1hIjTpvNFMPOwQEWWrZmnQNWMLoMLKZMvEA90